import os
from fpdf import FPDF, XPos, YPos
from io import BytesIO


class PDFService(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 24)
        self.set_text_color(20, 184, 166)
        self.cell(0, 15, "SmartTravel Itinerary", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by SmartTravel AI", border=0, align="C")

    @staticmethod
    def generate_itinerary_pdf(itinerary, user):
        pdf = PDFService()
        pdf.alias_nb_pages()
        pdf.add_page()

        # Header details
        pdf.set_font("helvetica", "B", 16)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(0, 10, f"Prepared for: {user.name}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("helvetica", "", 12)
        pdf.cell(0, 8, f"Destination: {itinerary.destination.title()}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        start = itinerary.start_date.strftime('%b %d, %Y') if hasattr(itinerary.start_date, 'strftime') else str(itinerary.start_date)[:10]
        end = itinerary.end_date.strftime('%b %d, %Y') if hasattr(itinerary.end_date, 'strftime') else str(itinerary.end_date)[:10]

        pdf.cell(0, 8, f"Dates: {start} to {end}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.cell(0, 8, f"Total Budget: ${itinerary.total_budget:,.2f}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(10)

        # Flights
        pdf.set_font("helvetica", "B", 14)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 10, " Flights", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        pdf.set_font("helvetica", "", 11)
        if itinerary.flights:
            for f in itinerary.flights:
                line = f"- {f.airline} ({f.flight_number}): {f.departure_airport} -> {f.arrival_airport} | ${f.price:,.2f}"
                pdf.cell(0, 8, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        else:
            pdf.cell(0, 8, "No flights booked.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(5)

        # Hotels
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(0, 10, " Accommodation", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        pdf.set_font("helvetica", "", 11)
        if itinerary.hotels:
            for h in itinerary.hotels:
                pdf.cell(0, 8, f"- {h.hotel_name} | {h.room_type} | ${h.total_price:,.2f}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        else:
            pdf.cell(0, 8, "No accommodation booked.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(5)

        # Activities
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(0, 10, " Curated Activities", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        pdf.set_font("helvetica", "", 11)
        if itinerary.activities:
            for a in itinerary.activities:
                pdf.cell(0, 8, f"- {a.activity_name} ({a.duration_hours}h) | ${a.price:,.2f}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                safe_desc = str(a.description or "").encode('latin-1', 'replace').decode('latin-1')
                pdf.set_font("helvetica", "I", 9)
                pdf.multi_cell(0, 6, f"  {safe_desc}")
                pdf.set_font("helvetica", "", 11)
                pdf.ln(2)
        else:
            pdf.cell(0, 8, "No activities booked.", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Return as BytesIO — output() returns bytes in fpdf2 v2.x
        output = BytesIO()
        output.write(pdf.output())
        output.seek(0)
        return output
